// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ecexzlqjobqajfhxmiaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZXh6bHFqb2JxYWpmaHhtaWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODcxODcsImV4cCI6MjA1NzM2MzE4N30.J7o9ClLseeAwywcaULst7_SYcKmOM3uNHaWn5msAPsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);